In [1]:
import pandas as pd

df = pd.read_csv("/media/8TB_hardisk/sangam/timeseries_forecasting/data/kaist/5/combined_sorted_data_normalization_5min_with_CT_PZ.csv")

In [2]:
df.head()

,scenario_number,TIME,PPS,TGRCS(10),TGRCS(15),ZWV,PSGGEN(1),ZWDC2SG(1)S,MAX_CET,CTMTP,...,RCP_pump,HX,HPI,LPI,CNMT_Spray,MDAFW,Charging_pump,SAMG_1,SAMG_2,SAMG_3
0,0.0,0.0,0.894904,0.44356,0.268530,0.999426,0.835792,0.898000,0.102260,0.005456,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.894904,0.44356,0.268530,0.999426,0.835792,0.898000,0.102260,0.005456,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.894904,0.44356,0.268530,0.999426,0.835792,0.898000,0.102260,0.005456,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,318.0,0.813388,0.44818,0.258738,0.999426,0.993379,0.744234,0.103410,0.006277,...,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
4,0.0,589.0,0.784276,0.44202,0.252863,0.999426,0.991112,0.760981,0.101876,0.006487,...,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0

In [3]:
len(df.columns)

22

In [4]:
df.columns

Index(['scenario_number', 'TIME', 'PPS', 'TGRCS(10)', 'TGRCS(15)', 'ZWV',
       'PSGGEN(1)', 'ZWDC2SG(1)S', 'MAX_CET', 'CTMTP', 'PZRP', 'PZRWL',
       'RCP_pump', 'HX', 'HPI', 'LPI', 'CNMT_Spray', 'MDAFW', 'Charging_pump',
       'SAMG_1', 'SAMG_2', 'SAMG_3'],
      dtype='object')

In [5]:
len(df['scenario_number'].unique())

11000

In [6]:
import pandas as pd
import numpy as np

def train_test_split_by_scenario(df: pd.DataFrame, split: float = 0.9, shuffle: bool = False, random_state: int = None):
    """
    Split the dataframe into train and test sets by scenario_number.
    Entire scenarios go either into train or test.

    Parameters
    ----------
    df : pd.DataFrame
        The dataframe with a 'scenario_number' column.
    split : float, optional (default=0.9)
        Fraction of scenarios to include in the train set.
    shuffle : bool, optional (default=False)
        Whether to shuffle the scenarios before splitting.
    random_state : int, optional (default=None)
        Random seed for reproducibility when shuffle=True.

    Returns
    -------
    train_df : pd.DataFrame
        Data for training (split% of scenarios).
    test_df : pd.DataFrame
        Data for testing (remaining scenarios).
    """
    scenarios = df["scenario_number"].unique()

    if shuffle:
        rng = np.random.default_rng(seed=random_state)
        rng.shuffle(scenarios)

    n_train = int(len(scenarios) * split)

    train_scenarios = scenarios[:n_train]
    test_scenarios = scenarios[n_train:]

    train_df = df[df["scenario_number"].isin(train_scenarios)]
    test_df = df[df["scenario_number"].isin(test_scenarios)]

    return train_df, test_df

In [7]:
train_df, test_df = train_test_split_by_scenario(df, split=0.9, shuffle = True, random_state = 42)

In [8]:
train_df.head()

,scenario_number,TIME,PPS,TGRCS(10),TGRCS(15),ZWV,PSGGEN(1),ZWDC2SG(1)S,MAX_CET,CTMTP,...,RCP_pump,HX,HPI,LPI,CNMT_Spray,MDAFW,Charging_pump,SAMG_1,SAMG_2,SAMG_3
0,0.0,0.0,0.894904,0.44356,0.268530,0.999426,0.835792,0.898000,0.102260,0.005456,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.894904,0.44356,0.268530,0.999426,0.835792,0.898000,0.102260,0.005456,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.894904,0.44356,0.268530,0.999426,0.835792,0.898000,0.102260,0.005456,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,318.0,0.813388,0.44818,0.258738,0.999426,0.993379,0.744234,0.103410,0.006277,...,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
4,0.0,589.0,0.784276,0.44202,0.252863,0.999426,0.991112,0.760981,0.101876,0.006487,...,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0

In [9]:
test_df.tail()

,scenario_number,TIME,PPS,TGRCS(10),TGRCS(15),ZWV,PSGGEN(1),ZWDC2SG(1)S,MAX_CET,CTMTP,...,RCP_pump,HX,HPI,LPI,CNMT_Spray,MDAFW,Charging_pump,SAMG_1,SAMG_2,SAMG_3
9489510,11477.0,258006.50,0.035217,0.485087,0.263575,0.000986,0.987608,0.914714,0.199605,0.705748,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9489511,11477.0,258306.50,0.035322,0.483578,0.263503,0.000986,0.987604,0.914521,0.199605,0.706934,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9489512,11477.0,258606.50,0.035380,0.484576,0.263427,0.000986,0.987605,0.914327,0.199605,0.708112,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9489513,11477.0,258906.50,0.035383,0.486548,0.263391,0.000986,0.987609,0.914128,0.199605,0.709276,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9489514,11477.0,259200.05,0.035452,0.483533,0.285132,0.000986,0.987673,0.913919,0.199605,0.710424,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [10]:
root_dir = "/media/8TB_hardisk/sangam/timeseries_forecasting/data/kaist/5"
train_file = "combined_sorted_data_normalization_5min_with_CT_PZ_train.csv"
test_file = "combined_sorted_data_normalization_5min_with_CT_PZ_test.csv"
train_df.to_csv(f"{root_dir}/{train_file}", index=False)
test_df.to_csv(f"{root_dir}/{test_file}", index=False)

In [11]:
df.columns

Index(['scenario_number', 'TIME', 'PPS', 'TGRCS(10)', 'TGRCS(15)', 'ZWV',
       'PSGGEN(1)', 'ZWDC2SG(1)S', 'MAX_CET', 'CTMTP', 'PZRP', 'PZRWL',
       'RCP_pump', 'HX', 'HPI', 'LPI', 'CNMT_Spray', 'MDAFW', 'Charging_pump',
       'SAMG_1', 'SAMG_2', 'SAMG_3'],
      dtype='object')